spring:
  application:
    name: feign-client
  mvc:
    throw-exception-if-no-handler-found: true

server:
  port: 8888

eureka:
  client:
    preferSameZone: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true


bookmark-service:
  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    DeploymentContextBasedVipAddress: bookmark-service
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ServerListRefreshInterval: 2000
