spring:
  application:
    name: bookmark-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    healthcheck:
      enabled: true
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1


  instance:
    instanceId: ${spring.application.name}:{spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

server:
  port: 0
