spring:
  application:
    name: treatment-service

eureka:
  client:
    preferSameZone: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    healthcheck:
      enabled: true

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN RSA PUBLIC KEY-----
          MIIBCgKCAQEA07/4DxKS+vHMDeQMCfhd106LfDkyIGNyZGNH3OhA0o3c0PU7ui20
          3tZqD5V2oWBxkyqus1j0ZDYl74u79ZpKFTHgoowZcwMYxNjUNqLczJqpkOFXR1Nv
          dI/5h87rzwsJHKqJ0ntG4kHJmCQl9Wmdi8ZXDLsV+hoQKFKD4w3A8NCO1cnaPQwM
          DnY4eRYT8N9K6Wb2k8lYzY1NQ9nTijswWFLm8Qp2uyLqtTWbZvn/JaksRdNTv6J6
          SnSeQnw5sAKJUCLLx/zDVH6ALbIjsT7/aZY/N6e5ByQU4yz+TJHZ7wKruM4jKVD3
          PsSW7TM339qmdsxVtulyGPbaRn6Swsx4kQIDAQAB
          -----END RSA PUBLIC KEY-----

  instance:
    instanceId: ${spring.application.name}:{spring.application.instance_id:${random.value}}
    prefer-ip-address: true

server:
  port: 0
