spring:
  application:
    name: bookmark-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    healthcheck:
      enabled: true


  instance:
    instanceId: ${spring.application.name}:{spring.application.instance_id:${random.value}}
    prefer-ip-address: true

server:
  port: 0
