spring:
  application:
    name: microservice-client

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true


bookmark-service:
  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    DeploymentContextBasedVipAddress: bookmark-service
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
