spring:
  application:
    name: microservice-client

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    healthcheck:
      enabled: true
    refresh:
      interval: 3

bookmark-service:
  ribbon:
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ServerListRefreshInterval: 2000
    DeploymentContextBasedVipAddress: bookmark-service
