server:
    port: 8891

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BAXSEC
    username: postgres
    password: SYS
    driver-class-name: org.postgresql.Driver
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        healthCheckInterval: 30s

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN RSA PUBLIC KEY-----
          MIIBCgKCAQEA07/4DxKS+vHMDeQMCfhd106LfDkyIGNyZGNH3OhA0o3c0PU7ui20
          3tZqD5V2oWBxkyqus1j0ZDYl74u79ZpKFTHgoowZcwMYxNjUNqLczJqpkOFXR1Nv
          dI/5h87rzwsJHKqJ0ntG4kHJmCQl9Wmdi8ZXDLsV+hoQKFKD4w3A8NCO1cnaPQwM
          DnY4eRYT8N9K6Wb2k8lYzY1NQ9nTijswWFLm8Qp2uyLqtTWbZvn/JaksRdNTv6J6
          SnSeQnw5sAKJUCLLx/zDVH6ALbIjsT7/aZY/N6e5ByQU4yz+TJHZ7wKruM4jKVD3
          PsSW7TM339qmdsxVtulyGPbaRn6Swsx4kQIDAQAB
          -----END RSA PUBLIC KEY-----
      #userInfoUri: https://bax-poc.auth0.com/userinfo